name=EEGLTWM
version=0.0.1
author=The Makers
sentence=Beginner-friendly EEG library for arduino
paragraph=Simplifies EEG signals into usable events like blink and focus
category=Signal Input/Output
architectures=*
